use_ddp: True   # whether to use DataDistributedParallel, for multi-gpus.
port:   12345 # the port for the DataDistributedParallel training.

resume: /DATA/bvac/personal/reserach/font_gen/mxfont/result_ch_korean_eng/checkpoints/1400000.pth
work_dir: ./result_ch_korean_eng   # the directory to save checkpoints, validation images, and the log.

decomposition: data/ch_korean_eng_decomposition.json   # path to the "decomposition rule" file.
primals: data/ch_korean_eng_primals.json   # path to the "primals" file.

dset:   # leave blank
  train:   # leave blank
    data_dir: ../fonts_ch_korean_eng   # path to .ttf files for the training
  val:   # leave blank
    data_dir: data/ttfs/val   # path to .ttf files for the validation
    source_font: data/ttfs/val/MaShanZheng-Regular.ttf   # path to the .ttf file used as the source font during the validation


batch_size: 32

max_iter: 1600000
print_freq: 1000
val_freq: 10000
save_freq: 10000